### ISSUE TITLE
It's demo time

### ISSUE THREAD

**Issue by bryanpedini** [rls-moe/nyx#7]
Didn't you want a demo server?
After creating the Docker image, I then proceeded to build another one on top of it, with a default SQLite3 database with admin informations changed, and predefined boards (with captcha disabled).

And thanks to the power of Nginx's locations and a cronjob that restarts the Docker container, effectively resetting the entire website, to prevent database growth and too much spam/flood, there you have it [here](https://nyx.demo.bjphoster.com/).

**Comment by bryanpedini** [comment]
Demo done (even tho the docker container still doesn't run the way I would like to, so I put the app in the host machine).

**Comment by tscs37** [comment]
Nice, that's good to hear. The limiting issue in docker is probably that nyx uses the local hostname as a storage key, so new containers don't share data except user info.

That might be a target for a possible rewrite; the framework I wrote this on is positively ancient and outdated and I think it could benefit from me writing it out again in Rust if I find the time, since that's my current pet language. But again, something for the future to think about, I haven't worked on this in forever (I'd hate to have this die)

**Comment by bryanpedini** [comment]
I figured that Docker issue out: indeed, assigning "yoda.servers.bjphoster.com" as hostname in the Docker container, made my demo boards pop up like nothing happened.

For the framework tho, I would love it to see it rewritten but still in Go...
Talking about rewriting... does the app support MySQL 8 as a database backend? I would rather liked demoing it on MySQL and rewrite the entire database with a SQL file backup instead of making a custom script that periodically stops the service, replace the database file with a previous backup and starts the service back on.

**Comment by tscs37** [comment]
It uses BuntDB, a Key-Value database, doesn't rely on anything SQL, which is fast enough in most cases. It doesn't have any ORM so any SQL support would mean a complete rewrite of the backend.

**Comment by bryanpedini** [comment]
Meh...

I understand...
